# Generated by Django 4.2.1 on 2024-02-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ash_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.CharField(max_length=3000)),
                ("Ash_message", models.CharField(max_length=6000)),
            ],
        ),
    ]
