# Generated by Django 4.2.1 on 2024-02-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ash_model",
            name="username",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
