# Generated by Django 4.2.1 on 2024-02-04 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signin", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Signin",
        ),
    ]
